"""
Integration tests for the API using TEST_CASES extracted from each scraper.

Loads test_cases.json (generated by generate_test_lookup.py) and parametrizes
one test per scraper, calling the /api/v1/lookup endpoint with the first
test case's params.

Usage:
    uv run pytest tests/test_api_scrapers.py -v
    uv run pytest tests/test_api_scrapers.py -v -k "aberdeen"
"""

import json
from pathlib import Path

import httpx
import pytest
import pytest_asyncio
from asgi_lifespan import LifespanManager

from api.main import app

TEST_CASES_PATH = Path(__file__).parent / "test_cases.json"
BASE_URL = "http://testserver/api/v1"


def _load_test_cases() -> list[tuple[str, str, dict]]:
    """Load test cases and return (council, label, params) tuples — first case per scraper."""
    data = json.loads(TEST_CASES_PATH.read_text())
    cases = []
    for council, entries in sorted(data.items()):
        if entries:
            first = entries[0]
            cases.append((council, first["label"], first["params"]))
    return cases


TEST_DATA = _load_test_cases()


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def client():
    """Shared async client with app lifespan (startup/shutdown) managed."""
    async with LifespanManager(app) as manager:
        transport = httpx.ASGITransport(app=manager.app)
        async with httpx.AsyncClient(
            transport=transport, base_url=BASE_URL, timeout=120
        ) as c:
            yield c


@pytest.mark.parametrize(
    "council,label,params",
    TEST_DATA,
    ids=[f"{cc}_{ll}" for cc, ll, _ in TEST_DATA],
)
@pytest.mark.asyncio(loop_scope="session")
async def test_lookup(
    client: httpx.AsyncClient, council: str, label: str, params: dict
):
    """Test that the lookup endpoint returns a valid response for each scraper."""
    params = dict(params)  # copy so pop doesn't mutate shared data
    uprn = params.pop("uprn", params.pop("address_id", "0"))
    query = {"council": council, **params}

    resp = await client.get(f"/lookup/{uprn}", params=query)

    assert resp.status_code == 200, (
        f"{council} ({label}): expected 200, got {resp.status_code} — {resp.text}"
    )
    data = resp.json()
    assert "collections" in data, f"{council}: response missing 'collections' key"
