"""
Integration tests for the API using TEST_CASES extracted from each scraper.

Loads test_cases.json (generated by generate_test_lookup.py) and runs all
scraper lookups concurrently via asyncio.gather for speed, then reports
each scraper as its own parametrized test for maximum failure detail.

Usage:
    uv run pytest tests/test_api_scrapers.py -v
    uv run pytest tests/test_api_scrapers.py -v -k "aberdeen"
"""

import asyncio
import json
from pathlib import Path

import httpx
import pytest
import pytest_asyncio
from asgi_lifespan import LifespanManager

from api.main import app

TEST_CASES_PATH = Path(__file__).parent / "test_cases.json"
BASE_URL = "http://testserver/api/v1"

MAX_CONCURRENCY = 40


def _load_test_cases() -> list[tuple[str, str, dict]]:
    """Load test cases and return (council, label, params) tuples — first case per scraper."""
    data = json.loads(TEST_CASES_PATH.read_text())
    cases = []
    for council, entries in sorted(data.items()):
        if entries:
            first = entries[0]
            cases.append((council, first["label"], first["params"]))
    return cases


TEST_DATA = _load_test_cases()


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def client():
    """Shared async client with app lifespan (startup/shutdown) managed."""
    async with LifespanManager(app) as manager:
        transport = httpx.ASGITransport(app=manager.app)
        async with httpx.AsyncClient(
            transport=transport, base_url=BASE_URL, timeout=120
        ) as c:
            yield c


async def _lookup(
    client: httpx.AsyncClient,
    semaphore: asyncio.Semaphore,
    council: str,
    label: str,
    params: dict,
) -> dict:
    """Run a single lookup, returning a result dict with all diagnostic info."""
    params = dict(params)
    uprn = params.pop("uprn", params.pop("address_id", "0"))
    query = {"council": council, **params}

    result = {
        "council": council,
        "label": label,
        "uprn": uprn,
        "query_params": query,
    }

    async with semaphore:
        try:
            resp = await client.get(f"/lookup/{uprn}", params=query)
        except Exception as exc:
            result["error"] = f"{type(exc).__name__}: {exc}"
            return result

    result["status_code"] = resp.status_code
    result["response_body"] = resp.text[:1000]

    try:
        result["response_json"] = resp.json()
    except (json.JSONDecodeError, ValueError):
        pass

    return result


# Session-scoped cache: all lookups run once concurrently, shared across parametrized tests
_results_cache: dict[str, dict] = {}


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def all_results(client: httpx.AsyncClient):
    """Run all scraper lookups concurrently and cache the results."""
    if not _results_cache:
        semaphore = asyncio.Semaphore(MAX_CONCURRENCY)
        results = await asyncio.gather(
            *[
                _lookup(client, semaphore, council, label, params)
                for council, label, params in TEST_DATA
            ]
        )
        for r in results:
            _results_cache[f"{r['council']}_{r['label']}"] = r
    return _results_cache


@pytest.mark.asyncio(loop_scope="session")
@pytest.mark.parametrize(
    "council, label, params",
    TEST_DATA,
    ids=[f"{council}_{label}" for council, label, _ in TEST_DATA],
)
async def test_scraper_lookup(all_results, council: str, label: str, params: dict):
    """Check the cached result for a single scraper lookup."""
    key = f"{council}_{label}"
    result = all_results[key]

    # Request-level exception
    if "error" in result:
        pytest.fail(
            f"Request exception for {council} ({label})\n"
            f"  UPRN/address_id: {result['uprn']}\n"
            f"  Query params:    {json.dumps(result['query_params'], indent=2)}\n"
            f"  Exception:       {result['error']}"
        )

    status = result["status_code"]
    body_json = result.get("response_json")

    # Non-200 status
    if status != 200:
        detail = ""
        if body_json and "detail" in body_json:
            detail = f"\n  Error detail:    {body_json['detail']}"
        pytest.fail(
            f"Expected 200, got {status} for {council} ({label})\n"
            f"  UPRN/address_id: {result['uprn']}\n"
            f"  Query params:    {json.dumps(result['query_params'], indent=2)}\n"
            f"  Status code:     {status}{detail}\n"
            f"  Response body:   {result['response_body'][:500]}"
        )

    # Non-JSON response
    assert body_json is not None, (
        f"Response is not valid JSON for {council} ({label})\n"
        f"  UPRN/address_id: {result['uprn']}\n"
        f"  Response body:   {result['response_body'][:500]}"
    )

    # Missing collections key
    assert "collections" in body_json, (
        f"Response missing 'collections' key for {council} ({label})\n"
        f"  UPRN/address_id: {result['uprn']}\n"
        f"  Response keys:   {list(body_json.keys())}\n"
        f"  Response body:   {json.dumps(body_json, indent=2)[:500]}"
    )
