"""
Integration tests for the API using TEST_CASES extracted from each scraper.

Loads test_cases.json (generated by generate_test_lookup.py) and runs all
scraper lookups concurrently via asyncio.gather for speed.

Usage:
    uv run pytest tests/test_api_scrapers.py -v
    uv run pytest tests/test_api_scrapers.py -v -k "aberdeen"
"""

import asyncio
import json
from pathlib import Path

import httpx
import pytest
import pytest_asyncio
from asgi_lifespan import LifespanManager

from api.main import app

TEST_CASES_PATH = Path(__file__).parent / "test_cases.json"
BASE_URL = "http://testserver/api/v1"

MAX_CONCURRENCY = 20


def _load_test_cases() -> list[tuple[str, str, dict]]:
    """Load test cases and return (council, label, params) tuples — first case per scraper."""
    data = json.loads(TEST_CASES_PATH.read_text())
    cases = []
    for council, entries in sorted(data.items()):
        if entries:
            first = entries[0]
            cases.append((council, first["label"], first["params"]))
    return cases


TEST_DATA = _load_test_cases()


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def client():
    """Shared async client with app lifespan (startup/shutdown) managed."""
    async with LifespanManager(app) as manager:
        transport = httpx.ASGITransport(app=manager.app)
        async with httpx.AsyncClient(
            transport=transport, base_url=BASE_URL, timeout=120
        ) as c:
            yield c


async def _lookup(
    client: httpx.AsyncClient,
    semaphore: asyncio.Semaphore,
    council: str,
    label: str,
    params: dict,
) -> str | None:
    """Run a single lookup, returning an error string or None on success."""
    params = dict(params)
    uprn = params.pop("uprn", params.pop("address_id", "0"))
    query = {"council": council, **params}

    async with semaphore:
        try:
            resp = await client.get(f"/lookup/{uprn}", params=query)
        except Exception as exc:
            return f"FAIL {council} ({label}): {exc}"

    if resp.status_code != 200:
        return f"FAIL {council} ({label}): expected 200, got {resp.status_code} — {resp.text}"
    data = resp.json()
    if "collections" not in data:
        return f"FAIL {council} ({label}): response missing 'collections' key"
    return None


@pytest.mark.asyncio(loop_scope="session")
async def test_all_scrapers(client: httpx.AsyncClient):
    """Test all scrapers concurrently via asyncio.gather."""
    semaphore = asyncio.Semaphore(MAX_CONCURRENCY)
    results = await asyncio.gather(
        *[
            _lookup(client, semaphore, council, label, params)
            for council, label, params in TEST_DATA
        ]
    )
    failures = [r for r in results if r is not None]
    if failures:
        pytest.fail(f"{len(failures)} scraper(s) failed:\n" + "\n".join(failures))
