"""
Module for processing household waste collection data from UK councils.

This module fetches council information and attempts to locate
council waste collection URLs by finding and parsing sitemaps.

Note: Before running this script, you must first run download_nspl.py to download
the postcode data and save it as data/nspl.parquet.
"""

import polars as pl
import httpx
import asyncio
from urllib.parse import urlparse
import xml.etree.ElementTree as ET
from typing import List, Optional
from pathlib import Path
import logging
import time

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


def get_postcode_data(
    nspl_path: str = "data/nspl.parquet",
) -> pl.DataFrame:
    """
    Loads the National Statistics Postcode Lookup (NSPL) data from a parquet file.

    The parquet file should be generated by running download_nspl.py first.

    Args:
        nspl_path: Path to the NSPL parquet file. Defaults to data/nspl.parquet.

    Returns:
        A Polars DataFrame containing postcode (pcd) and local authority (laua) columns.
        Postcodes are normalized (spaces removed).

    Raises:
        FileNotFoundError: If the parquet file doesn't exist.
            Run download_nspl.py first to generate the file.
    """
    parquet_file = Path(nspl_path)

    if not parquet_file.exists():
        raise FileNotFoundError(
            f"NSPL data file not found at {nspl_path}. "
            "Please run 'uv run src/finding_data/download_nspl.py' first to download the data."
        )

    print(f"Loading NSPL postcode data from {nspl_path}...")
    postcodes_full = pl.read_parquet(nspl_path)
    print(f"Loaded {len(postcodes_full):,} postcodes.")

    return postcodes_full


def get_council_urls(
    govuk_council_urls: str = "https://govuk-app-assets-production.s3.eu-west-1.amazonaws.com/data/local-links-manager/links_to_services_provided_by_local_authorities.csv",
) -> pl.DataFrame:
    """
    Fetches council service URLs from GOV.UK and extracts base domain URLs.

    This function downloads the GOV.UK council services CSV, filters for household waste
    collection information, extracts the top-level domain (TLD) from each URL, and
    returns a deduplicated list of council websites.

    Args:
        govuk_council_urls: URL to the GOV.UK council services CSV file.

    Returns:
        A Polars DataFrame with columns:
            - Authority Name: The name of the local authority
            - GSS: The Government Statistical Service code
            - URL: The base domain URL (e.g., https://example.gov.uk/)

    Raises:
        requests.RequestException: If the CSV download fails.
    """
    print("Fetching council waste collection URLs...")
    la_urls = (
        pl.read_csv(govuk_council_urls)
        .select(
            ["Authority Name", "GSS", "URL"],
        )
        .filter(pl.col("URL").is_not_null())
        # Extract base domain (scheme + netloc)
        .with_columns(
            pl.col("URL")
            .map_elements(
                lambda url: f"{urlparse(url).scheme}://{urlparse(url).netloc}/",
                return_dtype=pl.String,
            )
            .alias("URL")
        )
        # Filter out invalid URLs
        .filter(
            (pl.col("URL").str.starts_with("http://") | pl.col("URL").str.starts_with("https://")) &
            (~pl.col("URL").str.contains(":///"))
        )
        # Upgrade http to https for consistency
        .with_columns(
            pl.col("URL").str.replace("http://", "https://").alias("URL")
        )
        # Group by Authority Name and get first unique URL
        .unique(subset=["Authority Name"])
    )
    logger.info(f"Found {len(la_urls)} councils with valid URLs")
    return la_urls


async def try_sitemap_url(sitemap_url: str, client: httpx.AsyncClient) -> Optional[str]:
    """
    Attempts to access a single sitemap URL.

    Args:
        sitemap_url: The full sitemap URL to try.
        client: An httpx AsyncClient for making HTTP requests.

    Returns:
        The sitemap URL if successful, None otherwise.
    """
    try:
        response = await client.head(sitemap_url, follow_redirects=True, timeout=5.0)
        if response.status_code == 200:
            logger.debug(f"HEAD success: {sitemap_url}")
            return sitemap_url
        else:
            logger.debug(f"HEAD returned {response.status_code} for {sitemap_url}")
    except httpx.TimeoutException:
        logger.debug(f"HEAD timeout: {sitemap_url}")
    except httpx.ConnectError as e:
        error_msg = str(e).lower()
        if 'ssl' in error_msg or 'tls' in error_msg or 'certificate' in error_msg:
            logger.warning(f"🔒 HEAD TLS/SSL error for {sitemap_url}: {e}")
        else:
            logger.debug(f"HEAD connection error for {sitemap_url}: {type(e).__name__}: {e}")
    except Exception as e:
        error_msg = str(e).lower()
        if 'ssl' in error_msg or 'tls' in error_msg or 'certificate' in error_msg:
            logger.warning(f"🔒 HEAD TLS/SSL error for {sitemap_url}: {e}")
        else:
            logger.debug(f"HEAD failed for {sitemap_url}: {type(e).__name__}: {e}")

    # Try GET if HEAD fails
    try:
        response = await client.get(
            sitemap_url, follow_redirects=True, timeout=5.0
        )
        if response.status_code == 200:
            logger.debug(f"GET success: {sitemap_url}")
            return sitemap_url
        else:
            logger.debug(f"GET returned {response.status_code} for {sitemap_url}")
    except httpx.TimeoutException:
        logger.debug(f"GET timeout: {sitemap_url}")
    except httpx.ConnectError as e:
        error_msg = str(e).lower()
        if 'ssl' in error_msg or 'tls' in error_msg or 'certificate' in error_msg:
            logger.warning(f"🔒 GET TLS/SSL error for {sitemap_url}: {e}")
        else:
            logger.debug(f"GET connection error for {sitemap_url}: {type(e).__name__}: {e}")
    except Exception as e:
        error_msg = str(e).lower()
        if 'ssl' in error_msg or 'tls' in error_msg or 'certificate' in error_msg:
            logger.warning(f"🔒 GET TLS/SSL error for {sitemap_url}: {e}")
        else:
            logger.debug(f"GET failed for {sitemap_url}: {type(e).__name__}: {e}")

    return None


async def check_robots_txt(url: str, client: httpx.AsyncClient) -> Optional[str]:
    """
    Checks robots.txt for sitemap directive.

    Args:
        url: Base URL of the website.
        client: An httpx AsyncClient for making HTTP requests.

    Returns:
        Sitemap URL if found in robots.txt, None otherwise.
    """
    robots_url = f"{url.rstrip('/')}/robots.txt"
    try:
        response = await client.get(robots_url, follow_redirects=True, timeout=5.0)
        if response.status_code == 200:
            # Parse robots.txt for Sitemap directive
            for line in response.text.split('\n'):
                if line.lower().startswith('sitemap:'):
                    sitemap_url = line.split(':', 1)[1].strip()
                    logger.debug(f"Found sitemap in robots.txt: {sitemap_url}")
                    return sitemap_url
    except Exception as e:
        logger.debug(f"Could not fetch robots.txt for {url}: {type(e).__name__}")
    return None


async def find_sitemap_for_url(
    council_name: str,
    url: str,
    client: httpx.AsyncClient,
) -> Optional[str]:
    """
    Attempts to find the sitemap URL for a given council website.

    First checks robots.txt for sitemap directive, then tries common sitemap locations.

    Args:
        council_name: Name of the council (for logging purposes).
        url: Base URL of the council website.
        client: An httpx AsyncClient for making HTTP requests.

    Returns:
        The URL of the sitemap if found, None otherwise.
    """
    start_time = time.time()
    logger.debug(f"Searching sitemap for {council_name} at {url}")

    # First, check robots.txt - much faster!
    sitemap_from_robots = await check_robots_txt(url, client)
    if sitemap_from_robots:
        # Verify the sitemap URL actually works
        verified = await try_sitemap_url(sitemap_from_robots, client)
        if verified:
            elapsed = time.time() - start_time
            logger.info(f"✓ Found sitemap via robots.txt for {council_name} in {elapsed:.1f}s: {verified}")
            return verified

    # If robots.txt didn't work, try common locations
    sitemap_suffixes = [
        "sitemap.xml",
        "sitemap_index.xml",
        "sitemap",
        "sitemap1.xml",
        "sitemap-index.xml",
    ]

    # Try all sitemap URLs in parallel
    sitemap_urls = [f"{url.rstrip('/')}/{suffix}" for suffix in sitemap_suffixes]
    tasks = [try_sitemap_url(sitemap_url, client) for sitemap_url in sitemap_urls]
    results = await asyncio.gather(*tasks)

    elapsed = time.time() - start_time

    # Return the first successful result
    for result in results:
        if result:
            logger.info(f"✓ Found sitemap for {council_name} in {elapsed:.1f}s: {result}")
            return result

    logger.warning(f"✗ No sitemap found for {council_name} after {elapsed:.1f}s: {url}")
    return None


async def find_sitemaps(councils_df: pl.DataFrame) -> pl.DataFrame:
    """
    Finds sitemap URLs for all councils in the DataFrame asynchronously.

    Args:
        councils_df: DataFrame containing council information with columns:
            - Authority Name
            - GSS
            - URL

    Returns:
        The input DataFrame with an additional 'sitemap_url' column containing
        the discovered sitemap URL (or None if not found).
    """
    print("\nFinding sitemaps for all councils...")

    async with httpx.AsyncClient() as client:
        tasks = [
            find_sitemap_for_url(row["Authority Name"], row["URL"], client)
            for row in councils_df.iter_rows(named=True)
        ]
        sitemap_urls = await asyncio.gather(*tasks)

    councils_df = councils_df.with_columns(
        pl.Series(name="sitemap_url", values=sitemap_urls)
    )

    return councils_df


async def find_waste_urls_in_sitemap(
    council_name: str, sitemap_url: str, client: httpx.AsyncClient
) -> List[str]:
    """
    Parses a sitemap and finds URLs related to household waste collection.

    Searches for URLs containing keywords like 'waste', 'bin', 'collection',
    'recycling', etc.

    Args:
        council_name: Name of the council (for logging purposes).
        sitemap_url: URL of the sitemap to parse.
        client: An httpx AsyncClient for making HTTP requests.

    Returns:
        A list of URLs from the sitemap that match waste collection keywords.
    """
    start_time = time.time()
    logger.debug(f"Parsing sitemap for {council_name}: {sitemap_url}")

    waste_keywords = [
        "waste",
        "bin",
        "collection",
        "recycling",
        "refuse",
        "rubbish",
        "household-waste",
    ]

    try:
        response = await client.get(sitemap_url, follow_redirects=True, timeout=15.0)
        if response.status_code != 200:
            logger.warning(f"Sitemap returned status {response.status_code} for {council_name}")
            return []

        # Parse XML
        root = ET.fromstring(response.content)

        # Handle XML namespaces
        namespaces = {"ns": "http://www.sitemaps.org/schemas/sitemap/0.9"}

        # Find all <loc> tags (URL locations in sitemap)
        urls = []
        for loc in root.findall(".//ns:loc", namespaces):
            if loc.text:
                urls.append(loc.text)

        # If no namespace, try without it
        if not urls:
            for loc in root.findall(".//loc"):
                if loc.text:
                    urls.append(loc.text)

        # Filter URLs containing waste-related keywords
        waste_urls = [
            url
            for url in urls
            if any(keyword in url.lower() for keyword in waste_keywords)
        ]

        elapsed = time.time() - start_time
        if waste_urls:
            logger.info(f"Found {len(waste_urls)} waste URLs for {council_name} in {elapsed:.1f}s")
        else:
            logger.debug(f"No waste URLs found in sitemap for {council_name} (checked {len(urls)} URLs in {elapsed:.1f}s)")

        return waste_urls[:5]  # Limit to 5 most relevant URLs

    except httpx.TimeoutException:
        elapsed = time.time() - start_time
        logger.warning(f"Timeout parsing sitemap for {council_name} after {elapsed:.1f}s")
        return []
    except httpx.ConnectError as e:
        elapsed = time.time() - start_time
        error_msg = str(e).lower()
        if 'ssl' in error_msg or 'tls' in error_msg or 'certificate' in error_msg:
            logger.warning(f"🔒 TLS/SSL error parsing sitemap for {council_name} after {elapsed:.1f}s: {e}")
        else:
            logger.error(f"Connection error parsing sitemap for {council_name} after {elapsed:.1f}s: {e}")
        return []
    except Exception as e:
        elapsed = time.time() - start_time
        error_msg = str(e).lower()
        if 'ssl' in error_msg or 'tls' in error_msg or 'certificate' in error_msg:
            logger.warning(f"🔒 TLS/SSL error parsing sitemap for {council_name} after {elapsed:.1f}s: {e}")
        else:
            logger.error(f"Error parsing sitemap for {council_name} after {elapsed:.1f}s: {type(e).__name__}: {e}")
        return []


async def process_council(
    council_name: str, gss: str, url: str, client: httpx.AsyncClient
) -> dict:
    """
    Processes a single council: finds sitemap and extracts waste collection URLs.

    This combines both sitemap discovery and URL extraction into a single operation
    for maximum parallelization across all councils.

    Args:
        council_name: Name of the council.
        gss: Government Statistical Service code.
        url: Base URL of the council website.
        client: An httpx AsyncClient for making HTTP requests.

    Returns:
        A dictionary containing:
            - Authority Name
            - GSS
            - URL
            - sitemap_url
            - waste_collection_urls
    """
    start_time = time.time()
    logger.info(f"⏳ Processing {council_name}...")

    # Find the sitemap
    sitemap_url = await find_sitemap_for_url(council_name, url, client)

    # If sitemap found, extract waste URLs
    waste_urls = []
    if sitemap_url:
        waste_urls = await find_waste_urls_in_sitemap(council_name, sitemap_url, client)

    elapsed = time.time() - start_time
    logger.info(f"✅ Completed {council_name} in {elapsed:.1f}s (sitemap: {'Yes' if sitemap_url else 'No'}, waste URLs: {len(waste_urls)})")

    return {
        "Authority Name": council_name,
        "GSS": gss,
        "URL": url,
        "sitemap_url": sitemap_url,
        "waste_collection_urls": waste_urls,
    }


async def process_all_councils(councils_df: pl.DataFrame, batch_size: int = 10) -> pl.DataFrame:
    """
    Processes all councils in small batches to avoid connection pool exhaustion.

    Args:
        councils_df: DataFrame containing council information with columns:
            - Authority Name
            - GSS
            - URL
        batch_size: Number of councils to process concurrently (default: 10)

    Returns:
        A DataFrame with columns:
            - Authority Name
            - GSS
            - URL
            - sitemap_url: The discovered sitemap URL (or None)
            - waste_collection_urls: List of relevant waste collection URLs
    """
    start_time = time.time()
    total_councils = len(councils_df)
    logger.info(f"\n{'='*80}")
    logger.info(f"🚀 Starting to process {total_councils} councils in batches of {batch_size}...")
    logger.info(f"{'='*80}\n")

    # Use a browser-like user agent to avoid being blocked
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
    }

    all_results = []

    async with httpx.AsyncClient(
        limits=httpx.Limits(max_connections=batch_size * 2, max_keepalive_connections=batch_size),
        timeout=httpx.Timeout(10.0, connect=5.0),
        headers=headers,
        follow_redirects=True
    ) as client:
        # Process councils in batches
        councils_list = list(councils_df.iter_rows(named=True))

        for i in range(0, len(councils_list), batch_size):
            batch = councils_list[i:i+batch_size]
            batch_num = i // batch_size + 1
            total_batches = (len(councils_list) + batch_size - 1) // batch_size

            logger.info(f"Processing batch {batch_num}/{total_batches} ({len(batch)} councils)...")

            tasks = [
                process_council(row["Authority Name"], row["GSS"], row["URL"], client)
                for row in batch
            ]

            results = await asyncio.gather(*tasks, return_exceptions=True)

            # Check for exceptions
            for j, result in enumerate(results):
                if isinstance(result, Exception):
                    logger.error(f"Council failed with exception: {result}")
                    row = batch[j]
                    all_results.append({
                        "Authority Name": row["Authority Name"],
                        "GSS": row["GSS"],
                        "URL": row["URL"],
                        "sitemap_url": None,
                        "waste_collection_urls": [],
                    })
                else:
                    all_results.append(result)

    elapsed = time.time() - start_time
    logger.info(f"\n{'='*80}")
    logger.info(f"🎉 Completed processing all {total_councils} councils in {elapsed:.1f}s ({elapsed/total_councils:.1f}s per council average)")
    logger.info(f"{'='*80}\n")

    # Convert results back to DataFrame
    return pl.DataFrame(all_results)


def get_pop_data(
    eng_wales_postcode_pop_url: str = "https://www.nomisweb.co.uk/output/census/2021/pcd_p002.csv",
    scotland_postcode_pop_url: str = "https://www.nrscotland.gov.uk/media/mafbfvmj/postcode2022_usualresidentpopulation.csv",
    ni_postcode_pop_url: str = "https://www.nisra.gov.uk/system/files/statistics/census-2021-person-and-household-estimates-for-postcodes-in-northern-ireland.xlsx",
) -> pl.DataFrame:
    """
    Downloads and combines population data for all UK postcodes.

    Fetches postcode-level population data from:
    - England and Wales (NOMIS)
    - Scotland (National Records of Scotland)
    - Northern Ireland (NISRA)

    Uses httpx for consistent, modern HTTP handling.

    Args:
        eng_wales_postcode_pop_url: URL for England and Wales postcode population data.
        scotland_postcode_pop_url: URL for Scotland postcode population data.
        ni_postcode_pop_url: URL for Northern Ireland postcode population data.

    Returns:
        A Polars DataFrame with columns:
            - postcode: Original postcode format
            - population: Number of usual residents
            - pcd: Normalized postcode (spaces removed)

    Raises:
        httpx.HTTPError: If any of the downloads fail.
    """
    print("Downloading population data for Scotland...")
    with httpx.stream(
        "GET", scotland_postcode_pop_url, follow_redirects=True
    ) as response:
        response.raise_for_status()
        scotland_content = response.read()

    scotland_postcode_pop = pl.read_csv(scotland_content).select(
        pl.col("Postcode").cast(pl.String).alias("postcode"),
        pl.col("UsualResidentPopulation")
        .cast(pl.Int64, strict=False)
        .alias("population"),
    )

    print("Downloading population data for England and Wales...")
    eng_wales_pop = pl.read_csv(eng_wales_postcode_pop_url).select(
        pl.col("Postcode").cast(pl.String).alias("postcode"),
        pl.col("Count").cast(pl.Int64, strict=False).alias("population"),
    )

    print("Downloading population data for Northern Ireland...")
    ni_postcode_pop = (
        pl.read_excel(
            ni_postcode_pop_url,
            sheet_name="Postcode",
            columns=[0, 4],
            has_header=False,
        )
        .slice(6)
        .select(
            pl.col("column_1").cast(pl.String).alias("postcode"),
            pl.col("column_2").cast(pl.Int64, strict=False).alias("population"),
        )
    )

    combined_df = (
        pl.concat(
            [
                scotland_postcode_pop,
                eng_wales_pop,
                ni_postcode_pop,
            ]
        )
        .drop_nulls()
        .with_columns(pl.col("postcode").str.replace_all(" ", "").alias("pcd"))
    )

    return combined_df


def get_populous_postcodes() -> pl.DataFrame:
    """
    Combines postcode geographic data with population data.

    Returns:
        A Polars DataFrame containing postcodes with their local authority codes
        and population data.
    """
    postcode_df = get_postcode_data()
    postcode_pop = get_pop_data()

    postcode_merge = postcode_df.join(
        postcode_pop, how="inner", left_on="pcd", right_on="pcd"
    ).drop("pcd")

    return postcode_merge


def main(output_filename: str = "data/postcodes_by_council.csv") -> pl.DataFrame:
    """
    Main function to combine all data sources and generate output.

    This function:
    1. Gets postcode and population data
    2. Fetches council URLs
    3. Processes all councils in parallel (finds sitemaps and waste URLs)
    4. Merges everything with postcode data
    5. Selects a representative high-population postcode for each council
    6. Saves the results to a CSV file

    Args:
        output_filename: Path where the output CSV should be saved.

    Returns:
        A Polars DataFrame containing the final merged data with columns:
            - Authority Name
            - URL: Council base URL
            - sitemap_url: Found sitemap URL
            - waste_collection_urls: List of relevant waste collection URLs
            - postcode: A representative postcode for the council area
    """
    # Get postcode and population data
    postcode_merge = get_populous_postcodes()

    # Get council URLs (now returns base domains)
    council_urls_df = get_council_urls()

    # Process all councils in parallel (find sitemaps AND waste URLs)
    council_urls_df = asyncio.run(process_all_councils(council_urls_df))

    # Convert list column to string before merging (CSV doesn't support nested data)
    council_urls_df = council_urls_df.with_columns(
        pl.col("waste_collection_urls")
        .list.join("|")
        .fill_null("")
        .alias("waste_collection_urls")
    )

    # Merge with postcode data
    print("Merging postcode and council URL data...")
    merged_df = (
        council_urls_df.join(postcode_merge, left_on="GSS", right_on="laua", how="left")
        .group_by("Authority Name", "URL", "sitemap_url", "waste_collection_urls")
        .agg(
            [
                pl.col("postcode")
                .filter(pl.col("population") >= pl.col("population").quantile(0.5))
                .first()
                .alias("postcode"),
            ]
        )
    )

    # Save the final enriched data to a CSV
    print(f"\nWriting full analyzed data to {output_filename}...")
    merged_df.write_csv(output_filename)
    print("Done.")

    return merged_df


if __name__ == "__main__":
    output = main()
